### ISSUE TITLE
Bower postinstall script failing

### ISSUE THREAD

**Issue by arjunnn** [abhididdigi/PolymerWedding#1]
Hey, I ran `npm install` and this is what happened. Script to install bower seems to result in the error. 

<details>
<summary>Stack trace for `bower@0.6.8 postinstall`</summary>
```
arjun@shadowfax:~/Documents/PolymerWedding$ npm install
npm WARN package.json Our_Wedding@0.1.1 No repository field.
npm WARN package.json Our_Wedding@0.1.1 No license field.
npm WARN deprecated graceful-fs@1.1.14: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
/
> bower@0.6.8 postinstall /home/arjun/Documents/PolymerWedding/node_modules/bower
> node cleanup


> Our_Wedding@0.1.1 postinstall /home/arjun/Documents/PolymerWedding
> ./node_modules/bower/bin/bower install

path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:479:5)
    at Object.<anonymous> (/home/arjun/Documents/PolymerWedding/node_modules/bower/lib/core/config.js:35:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/arjun/Documents/PolymerWedding/node_modules/bower/lib/commands/help.js:14:17)

npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! Our_Wedding@0.1.1 postinstall: `./node_modules/bower/bin/bower install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Our_Wedding@0.1.1 postinstall script './node_modules/bower/bin/bower install'.
npm ERR! This is most likely a problem with the Our_Wedding package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/bower/bin/bower install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs Our_Wedding
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls Our_Wedding
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/arjun/Documents/PolymerWedding/npm-debug.log
```
</details>

**Comment by arjunnn** [comment]
following instructions at https://www.polymer-project.org/1.0/docs/tools/polymer-cli rectifies the issue

**Comment by abhididdigi** [comment]
Yea, I guess this wasn't built as a native NodeJS app as it uses bower for package control...
